export const blogs = [
  {
    id: 1,
    title: "Lord of the Flies Book Review",
    image: "images/lotf.jpg",
    alt: "Lord of the Flies Book Review",
    route: "/lotf-review",
  },
  {
    id: 2,
    title: "Studying for AP Human Geography",
    image: "images/freshman-ap-study.jpg",
    alt: "Studying for AP Human Geography",
    route: "/ap-study-human-geography",
  },
  {
    id: 3,
    title: "How to start learning to code for free",
    image: "images/learn-to-code.jpg",
    alt: "How to start learning to code for free",
    route: "/learn-to-code-free",
  },
  {
    id: 4,
    title: "Coming Soon",
    image: "",
    alt: "Blog 4",
    route: "/coming-soon",
  },
  {
    id: 5,
    title: "Coming Soon",
    image: "",
    alt: "Blog 5",
    route: "/coming-soon",
  },
  {
    id: 6,
    title: "Coming Soon",
    image: "",
    alt: "Blog 6",
    route: "/coming-soon",
  },
  {
    id: 7,
    title: "Coming Soon",
    image: "",
    alt: "Blog 7",
    route: "/coming-soon",
  },
  {
    id: 8,
    title: "Coming Soon",
    image: "",
    alt: "Blog 8",
    route: "/coming-soon",
  },
  {
    id: 9,
    title: "Coming Soon",
    image: "",
    alt: "Blog 9",
    route: "/coming-soon",
  },
];
